#!/bin/sh

CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

# Branches protegidas
if [ "$CURRENT_BRANCH" != "develop" ] && \
   [ "$CURRENT_BRANCH" != "master" ] && \
   [ "$CURRENT_BRANCH" != "main" ]; then
  exit 0
fi

ALLOWED_USERS="wvsamancio@gmail.com"
CURRENT_USER=$(git config user.email)

for USER in $ALLOWED_USERS
do
  if [ "$CURRENT_USER" = "$USER" ]; then
    exit 0
  fi
done

REMOTE_CHANGES=$(git diff --name-only origin/$CURRENT_BRANCH...HEAD)

if echo "$REMOTE_CHANGES" | grep -E '(^|/)(package\.json|package-lock\.json)$' > /dev/null
then
  echo ""
  echo "❌ Push bloqueado na $CURRENT_BRANCH"
  echo "Você não pode alterar:"
  echo " - package.json"
  echo " - package-lock.json"
  echo ""
  exit 1
fi

exit 0